model_zip_name: pretrained_models.zip
model_loc: pretrained_models
model_weights_file_name: attention_dot_model.hdf5
model_doi: 8273608
it_toknizr_model_name: eng_tokenizer.pickle
en_toknizr_model_name: ita_tokenizer.pickle





